name: Socotech
favicon: null
layout_spectrum: 0.96462
typography_spectrum: 0.06702
title: Serving the Sonoma County Tech Startup Community
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
